### ISSUE TITLE
Tasks and objectives

### ISSUE THREAD

**Issue by PeterF521** [PeterF521/javascript-calculator#1]
**Objectives**
- [ ] Users can see current account and the result of last operation.
- [ ] Add number buttons, operators and AC and C (clear) feature.
- [ ] Users can only type until 9 numbers in a sequence, any other number should be ignored.
- [ ] Add equal button to calc an expression on any type of situation 
- [ ] Add event in AC/C button to clear an expression
- [ ] Add error when any operation exceed 9 numbers
- [ ] Add history calcs to be stored in a **history.json** file
---
**Tasks**
- [x] Create index.html, index.js and styles.ccs files
- [ ] Add buttons, result viewer and style them in `styles.css`
- [ ] Viewer should show the current operation/result
- [ ] Add event listener that when someone click on a number, the number should be:
  - Stored in a variable
  - Displayed on the viewer.
- [ ] Add event listener and toggle between C/AC in the buttons C/AC:
  - [ ] When someone click them, the current operation should be 100% ignored.
  - [ ] When someone click on equal button, the clear button content should be changed to `AC`, and vice-versa
- [ ] Operators buttons:
  - [ ] When someone click in a operator, the current result of current operation should be displayed
  - [ ] The selected operator should be stored in a `const`
- [ ] Equal button:
  - [ ] When someone click it, the current operation should be calculated and displayed on viewer
  - [ ] The entire calc should be stored into `history.json` file.
  - [ ] Variables/arrays used to store the calc informations should be cleared.
- [ ] If a number typed exceed 9 numbers and someone click in a number, it should be ignored.
- [ ] If a calc exceed 9 numbers of lenght, the calculator should return a error.
